apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-credentials
data:
  connection: bXktZGItY29ubmVjdGlvbi5leGFtcGxlLmNvbTozMzA2
  password: bXlmYW5jeXBhc3N3b3Jk
  username: bXlmYW5jeXVzZXI=

