apiVersion: v1
kind: Service
metadata:
  name: gitops-secrets-service
spec:
  type: NodePort
  selector:
    app: gitops-secrets-app
  ports:
      - nodePort: 31000
        protocol: TCP
        port: 8080